[build]
  publish = "."
  command = "echo 'No build command needed for static HTML'"

[build.environment]
  NODE_VERSION = "18"

# Configuration des en-têtes de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    # Cache statique pour les ressources
    Cache-Control = "public, max-age=3600"

# Configuration spécifique pour les fichiers de cache à long terme
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/json"

# Configuration pour les images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Redirections pour SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration pour le prérendu (optionnel)
[context.production.environment]
  NODE_ENV = "production"

# Configuration pour les fonctions (si jamais vous en ajoutez)
[functions]
  node_bundler = "esbuild"

# Configuration de traitement des formulaires (si besoin)
[[headers]]
  for = "/submit-form"
  [headers.values]
    Content-Type = "application/x-www-form-urlencoded"

# Headers spécifiques pour le Service Worker - important pour PWA
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"

# Headers pour le manifeste - important pour PWA
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/json"

# Compression des assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Encoding = "gzip"
